### ISSUE TITLE
Prime Music Stations do not play

### ISSUE THREAD

**Issue by darnells** [tiliado/nuvola-app-amazon-cloud-player#11] opened 2016-01-25 20:59 UTC
1. Open Amazon Cloud Player and login to Amazon Prime Music
2. Select 'Stations' from the menu panel
3. Select any station to play
   *\* A wait cursor appears on the selected station, but it never plays. The current panel is unresponsive until the Nuvola refresh or home buttons are pressed.

Playlists and albums work as expected.

Nuvola Player 3.0.0
Amazon Cloud Player 5.1
Linux Mint 17.0 (Ubuntu 14.04.3 LTS)

**Comment by SteVwonder** [comment] 2016-01-29 00:42
I was able to reproduce this issue both in Nuvolaplayer and WebKitGtk's Minibrowser, so I believe this is a WebKitGtk issue not a Nuvolaplayer issue.  @fenryxo, any suggestion on how to proceed?

**Comment by jiri-janousek** [comment] 2016-01-29 15:37
Hi @SteVwonder. I need more info :-) Which system do you use? Is the issue reproducible also in the latest Ubuntu/Fedora? Could you provide debugging output? See [Bug Reporting Guidelines](https://github.com/tiliado/nuvolaplayer/wiki/Bug-Reporting-Guidelines) for details.

**Comment by SteVwonder** [comment] 2016-01-30 16:02
OS: Ubuntu 14.04
Arch: x86_64
Window Manager: i3
Webkit: webkit2gtk-3.0 (0.26)
Nuvolaplayer: 3.0.0 (53b1d03843d1987c3510401da8959384fa25670e)

Nuvolaplayer run with debug output: https://gist.github.com/SteVwonder/efbd10ec37683a96046d

During that run, I played a playlist (which worked) then played a station (which didn't).  The WebkitWebProcess was using most of the CPU once I tried to play the station.

**Comment by jiri-janousek** [comment] 2016-01-30 16:22
I suppose these console error messages show up when you start playing a station. Am I right?

```
https://images-na.ssl-images-amazon.com/images/G/01/digital/music/player/web/assets
/20160202273992/digitalMusicWebPlayer._CB300720390_.js:2:
CONSOLE WARN: rxstores not found
https://images-na.ssl-images-amazon.com/images/G/01/digital/music/player/web/assets
/20160202273992/digitalMusicWebPlayer._CB300720390_.js:2:
 CONSOLE WARN: Cannot compute playbackState, nowPlaying is not available
```

Ubuntu 14.04 has a quite old WebKit (2.4.8-1ubuntu1~ubuntu14.04.1). Do you have a chance to check the issue in Ubuntu 15.10 (e.g. in VirtualBox)?

**Comment by SteVwonder** [comment] 2016-01-31 15:33
It plays correctly in Ubuntu 15.10.

**Comment by jiri-janousek** [comment] 2016-01-31 16:50
It's very likely that Prime Music Stations require a feature that is not present in WebKitGTK 2.4 (Ubuntu 14.04), but has been already implemented in a recent WebKitGTK. Is it possible to install [libwebkit2gtk-4.0-37 2.8.5+dfsg1-3](http://packages.ubuntu.com/wily/libwebkit2gtk-4.0-37) or  [libwebkit2gtk-4.0-37 2.6.2+dfsg1-4ubuntu1](http://packages.ubuntu.com/vivid/libwebkit2gtk-4.0-37) into Ubuntu 14.04 without entering a deep dependency hell?

**Comment by SteVwonder** [comment] 2016-02-04 22:20
I tried installing [libwebkit2gtk-4.0-37 2.6.2+dfsg1-4ubuntu1](http://packages.ubuntu.com/vivid/libwebkit2gtk-4.0-37) but I very quickly ran into a conflicting dependency.  It requires libatk1.0-0_2.14 but there is an existing dependency (on my clean install Ubuntu 14.04) on libatk1.0-0_2.10.  The dependency tree looks like:

```
libatk1.0 --> libatk1.0-dev --> libgtk2.0-dev
```

So I don't think this is feasible.  Hand compiling a new webkit2gtk (but still compiling against gtk3) might be more feasible.

**Comment by darnells** [comment] 2016-02-04 23:00
Since this is an out-of-date dependency problem, I feel that this analysis satisfactorily resolves the issue. I am an Ubuntu LTS user and the next LTS release is only two months away. My only other request would be that a note is placed in the nuvola-app-amazon-cloud-player readme stating that Prime Music Stations requires WebKitGTK 2.6.2 or greater.

**Comment by jiri-janousek** [comment] 2016-02-05 12:06
I've created a wiki page [Known Issues](https://github.com/tiliado/nuvola-app-amazon-cloud-player/wiki/Known-Issues). @SteVwonder, could you link it at `README.md` and close this ticket?

**Comment by SteVwonder** [comment] 2016-02-08 16:05
Updated README.md. Closing this issue.

**Closed as completed by SteVwonder** 2016-02-08 16:05 UTC

**Comment by jiri-janousek** [comment] 2016-04-16 19:49
The repository of **the Nuvola Player 3.1 Rolling Releases** now contains the WebKitGTK 2.8.5 packages for Ubuntu 14.04 and Nuvola Player packages for this distribution have been rebuilt to use them instead of the old WebKitGTK packages provided by Ubuntu. **This should fix all rendering/integration issues that had occurred only in Ubuntu 14.04.** Nuvola Patrons and other people with access to the rolling releases are welcome to try them out. If no problems are found, same trick will be made also for Nuvola Player 3.0 Stable Releases eventually (#216).
